#Selected theme
theme: jekyll-theme-midnight

#Configuration
title: David Pretola's Homepage
description: This page serves as my personal homepage.
show_downloads: false #do not provide a download URL

#Defaults
defaults:
 -
  scope:
   path: ""
  values:
   layout: "default"
