#Selected theme
theme: jekyll-theme-midnight

#Configuration
title: David Pretola Homepage
description: This page serves to be my personal homepage.

#Defaults
defaults:
 -
  scope:
   path: ""
  values:
   layout: "default"
